# Generated by Django 2.1.4 on 2018-12-08 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('FID', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('PID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Perishable', models.BooleanField(default=False)),
                ('Name', models.CharField(max_length=100)),
                ('OnHold', models.PositiveIntegerField()),
                ('MinQty', models.PositiveIntegerField()),
                ('Qty', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('VID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('DealsIn', models.ManyToManyField(through='StationaryAPI.Dealer', to='StationaryAPI.Item')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='CurrIt',
            field=models.ManyToManyField(through='StationaryAPI.CurrentItems', to='StationaryAPI.Item'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StationaryAPI.Item'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StationaryAPI.Vendor'),
        ),
        migrations.AddField(
            model_name='currentitems',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StationaryAPI.Faculty'),
        ),
        migrations.AddField(
            model_name='currentitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StationaryAPI.Item'),
        ),
    ]
