# Generated by Django 2.1.4 on 2018-12-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Approved', models.BooleanField(null=True)),
                ('Delivered', models.BooleanField(default=False)),
                ('OrderDate', models.DateField(auto_now_add=True)),
                ('DeliveryDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StationaryAPI.Item')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StationaryAPI.Order')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('OrderID', models.BigAutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateField(auto_now_add=True)),
                ('DeliveryDate', models.DateField()),
                ('Paid', models.BooleanField(default=False)),
                ('Delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyOrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qty', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StationaryAPI.Item')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StationaryAPI.SupplyOrder')),
            ],
        ),
        migrations.AlterField(
            model_name='faculty',
            name='CurrIt',
            field=models.ManyToManyField(related_name='curritems', through='StationaryAPI.CurrentItems', to='StationaryAPI.Item'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='DealsIn',
            field=models.ManyToManyField(related_name='deal', through='StationaryAPI.Dealer', to='StationaryAPI.Item'),
        ),
        migrations.AddField(
            model_name='supplyorder',
            name='items',
            field=models.ManyToManyField(related_name='supplyorditems', through='StationaryAPI.SupplyOrderItems', to='StationaryAPI.Item'),
        ),
        migrations.AddField(
            model_name='supplyorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vend', to='StationaryAPI.Vendor'),
        ),
        migrations.AddField(
            model_name='order',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact', to='StationaryAPI.Faculty'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orditems', through='StationaryAPI.OrderItems', to='StationaryAPI.Item'),
        ),
    ]
